### PR TITLE
The beginning

### PR DESCRIPTION
**Pull request by MHHukiewitz**

### CODE REVIEW

**Comment by MHHukiewitz** [comment]
wrong repo, lol

**Comment by s1korrrr** [comment]
Reservation-bound RSI capability slice published at dd2b84a7cf791d7091384bc09100f6f77b1c34cf. EntryIntent v2 publication now requires RSI plus portfolio-risk scope; v2 capabilities cannot use the plain consume path; reserved consumption atomically verifies exact intent, account, controller, notional, leverage, active state, and expiry, then persists reservation_id and audit evidence. Verification: 77 focused tests passed; PostgreSQL 17.10 migration/concurrency tests 2 passed; Alembic has one head; changed-file pre-commit and compile passed. Repository-wide pytest remains non-green at 871 passed / 17 skipped / 34 failures due unrelated missing historical RSI config/fixture files and the installed Hummingbot gateway enum stub; this was not treated as passing. Execution remains disabled and no router is registered in main.py.

**Comment by s1korrrr** [comment]
Published authenticated EntryIntent v2 authorization projection at exact SHA `a296cb42c53361b1ff125ec893a16eb43bd23161`.

Evidence:
- 74 focused RSI capability/portfolio tests passed
- `GET /rsi-v5/control/v1/intents/v2/{intent_id}/authorization` requires the same dual RSI/portfolio principal boundary and controller/account allowlists
- readiness requires an enabled ledger, identity-valid admitted/unexpired capability, and exact active/unexpired reservation geometry
- unknown/mismatched reservations are projected as absent; corrupt admitted capabilities fail bounded/closed
- reserved consumption returns the exact identity-validated canonical capability payload, excluding compact JWS/key material
- pre-commit, compileall, diff hygiene, and single Alembic head `20260811_0012_rsi_reserved_capability` passed

The projection is advisory only; the existing row-locked consume transaction remains authoritative. No app activation, credentials, executor submission, deployment, or execution route was added.

**Comment by s1korrrr** [comment]
Published exact EntryIntent/reservation time binding at SHA `8c78ea29293983b30db4b29c198cdf9f4f339c7e`.

Repair:
- plain and reserved consumption reject expired intents before capability mutation
- canonical intent expiry, persisted intent expiry, and reservation expiry must match exactly
- readiness projection uses the same time invariant
- reserved consume response returns committed UTC `consumed_at`; idempotent retries preserve the original value
- response validation proves `consumed_at` falls inside the returned signed capability validity interval

Evidence:
- 75 focused RSI capability/portfolio tests passed
- 2 PostgreSQL 17.10 migration/concurrency tests passed in an isolated temporary DB, removed afterward
- one Alembic head, pre-commit, compileall, and diff hygiene passed

No schema migration, activation, credentials, execution route, or external runtime call was added.

**Comment by s1korrrr** [comment]
Published bounded authenticated principal identity at SHA `1e24befc89685aa9c2901105312d4e04849f8ee3`.

Repair:
- principal subject now matches the persisted 256-character consumer identity boundary
- roles/controller/account scopes have explicit value and cardinality limits
- internal whitespace/control characters fail closed; identities are never truncated
- registry validation constructs the runtime principal contract, so invalid configuration fails at load/startup

Evidence: 59 focused principal/GeoShock/RSI/portfolio/AlphaLoop auth regressions passed; pre-commit, compileall, and diff hygiene passed. No credential source, permission grant, route registration, execution, or activation changed.

**Pull request closed without merging**
